version: '2'
services:
  frontend:
    build: ./frontend
    ports:
      - 8081:8080        
    environment :
      - SERVER_URL=http://backend:9000

  backend:
    build: ./backend
    ports:
      - 9000:9000
